---
title: "Linear splines in interrupted time series analysis"
output: html_notebook
---

```{r libs}
library(tidyverse)
```

```{r source}
source(file.path("..", "R", "spline_helpers.R"))
```


```{r sim-data}
set.seed(1235L)

actual_slope_ratio <- 0.94

timeseries_count_data <- tibble(
  month = seq.Date(from = as.Date("2021-01-01"),
                   to = as.Date("2022-12-01"),
                   by = "month"),
  num_pop = rpois(24L, lambda = 5000),
  month_no = c(1L:24L),
  intervention = rep(c(0L,1L), times = c(12L, 12L)),
  linpred = -3.5 + 0.02*month_no + 1*intervention +
    log(actual_slope_ratio) * intervention * month_no + log(num_pop),
  y = rpois(24L, lambda = exp(linpred)))
```

```{r fit-model}
glm1 <- glm(y ~ month_no * intervention,
            data = timeseries_count_data,
            offset = log(num_pop),
            family = poisson(link = "log"))

summary(glm1)
```

```{r}
exp(confint(glm1))
exp(coefficients(glm1)["month_no:intervention"])
```


```{r}
# Create new dataset with averaged values of covariates
data_new <- timeseries_count_data %>%
  group_by(intervention) %>%
  mutate(num_pop = mean(num_pop)) %>%
  ungroup()
```

```{r}
# Run model predictions on this averaged data
prediction_output <- predict(glm1,
                             newdata = data_new %>% select(-linpred, -y),
                             type = "response",
                             allow.new.levels = TRUE)
```

```{r}
# Add the predicted outcomes as a column to the averaged dataset
acts_preds <- data_new %>%
  cbind(prediction_output)
```

```{r}
acts_preds %>% select(month_no,
                      y,
                      prediction_output) %>% 
  ggplot2::ggplot(ggplot2::aes(x=month_no)) +
  ggplot2::geom_line(ggplot2::aes(y=prediction_output), colour = "blue") +
  ggplot2::geom_point(ggplot2::aes(y=y), colour = "black")
```

# Spline regression

```{r fit-spline-model}
library(splines)

glm1_spline <- glm(y ~ bs(month_no,
                          knots = c(12),
                          degree = 1L),
            data = timeseries_count_data,
            offset = log(num_pop),
            family = poisson(link = "log")
            )

summary(glm1_spline)
```


```{r}
# Run model predictions on this averaged data
prediction_output_spline <- predict(glm1_spline,
                             newdata = data_new %>% select(-linpred, -y),
                             type = "response",
                             allow.new.levels = TRUE)
```

```{r}
# Add the predicted outcomes as a column to the averaged dataset
acts_preds_spline <- data_new %>%
  cbind(prediction_output_spline)
```

```{r}
acts_preds_spline %>% select(month_no,
                      y,
                      prediction_output_spline) %>% 
  ggplot2::ggplot(ggplot2::aes(x=month_no)) +
  ggplot2::geom_line(ggplot2::aes(y=prediction_output_spline), colour = "blue") +
  ggplot2::geom_point(ggplot2::aes(y=y), colour = "black")
```


```{r}
spline_basis <- bs(timeseries_count_data$month_no,
                   knots = c(12),
                   degree = 1L)

spline_basis_df <- as_tibble(spline_basis) %>%
  mutate(x = row_number()) %>%
  pivot_longer(cols = -x) %>% 
  mutate(value = as.numeric(value))

ggplot(data = spline_basis_df,
       aes(x = x, y = value, colour = name)) +
  geom_line()
```

```{r}
bsfns <- get_basis_functions_for_linear_spline_with_one_knot(spline_basis)

bsfns

xt_vals <- timeseries_count_data %>% distinct(month_no) %>% arrange(month_no) %>% mutate(x = row_number()) %>% rename(X_t = month_no)


bsfns2 <- get_spline_eqns(spline_basis, x_vals = xt_vals)

all.equal(bsfns, bsfns2)

# We can also get the y = alpha + beta * x form of the linear predictor in
# each of the two regions (left and right of the knot)

coefs <- coefficients(glm1_spline)
names(coefs) <- NULL

alpha <- coefs[1]
beta1 <- coefs[2]
beta2 <- coefs[3]

lp <- expand_one_knot_spline_linear_predictor(beta1 = beta1,
                                        beta2 = beta2,
                                        alpha = alpha,
                                        basis_functions = bsfns,
                                        intercept = TRUE)

lp
```


```{r}
K <- get_linear_combination_for_difference_in_log_rr(spline_basis)

K
```

```{r}
library(multcomp)

### set up general linear hypothesis
glht_logslopediff <- glht(glm1_spline, linfct = K)
summary(glht_logslopediff)

glht_logslopediff_ci <- confint(glht_logslopediff)
glht_logslopediff_ci

exp(glht_logslopediff_ci$confint)
```




