---
title: "CLAHRC NWL Heart Failure Care Bundle Data Analysis - To Do List"
author: "Dr Thomas Woodcock"
date: "`r Sys.Date()`"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Vignette Title}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

## To Do
 
 1. $\checkmark$ Additional columns required in extract
  + $\checkmark$ Hospital site
  + $\checkmark$ Date of death in hospital
  + $\checkmark$ Discharge destination
 2. $\checkmark$ Missing data in `CSP...` columns over final six months of dataset
 3. $\checkmark$ Discrepancies between number of heart failure admissions in my analysis vs
 those in the presentation
 4. $\Box$ Control chart analysis for admissions (absolute and proportions)
 0. $\Box$ Time zone tests - and passes!!
 5. Link in
  + $\checkmark$ the care bundle data
  + $\checkmark$ national audit data
  + $\checkmark$ make national audit linkage site-sensitive
  + $\checkmark$ refactor linkage tests to use bundle/nicor id rather than row number
  + $\checkmark$ add pt 1087099 to nicor link test - to check, in conjunction with 1073855, that multi-site spells are linked to by any appropriate nicor records, but that cross-site linking doesn't happen.
 6. $\Box$ Examine for changes in demographics over the period
 8. $\Box$ Write research plan
 7. Analyse outcomes:
 
```{r xtable, echo=FALSE, results='asis', cache=TRUE}
  library(xtable)
  tcn <- c('Before-After Raw', 'Before-After Adjusted', 'Bundle Intervention Raw', 'Bundle Intervention Adjusted')
  trn <- c('LOS','Bed Days','Mortality','Readmissions')
r1 <- c('$\\Box$','$\\Box$','$\\Box$','$\\Box$')
r2 <- c('$\\Box$','$\\Box$','$\\Box$','$\\Box$')
r3 <- c('$\\Box$','$\\Box$','$\\Box$','$\\Box$')
r4 <- c('$\\Box$','$\\Box$','$\\Box$','$\\Box$')
tab1 <- matrix(c(r1,r2,r3,r4),nrow=4, ncol=4, byrow=TRUE)
rownames(tab1) <- trn
colnames(tab1) <- tcn
print(xtable(tab1, align="lcccc"), type="html")
```

